[package]
name = "kycom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.78"
bytes = "1.4.0"
kymux-types = { path = "../kymux-types" }
kyutil = { path = "../kyutil" }
log = "0.4.20"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "io-util", "sync", "macros", "net"] }
url = "2.5.2"

[features]
server = []
client = []
