[package]
name = "kymux"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
kycom = { path = "../kycom", optional = true }
kymux-types = { path = "../kymux-types" }
kynet = { path = "../kynet", optional = true }
kyproto = { path = "../kyproto", optional = true }

[features]
default = []
ipc = [
    "dep:kycom",
]
backend-quinn = [
    "kynet/kynet-quinn",
    "dep:kyproto",
]
backend-wtransport = [
    "kynet/kynet-wtransport",
    "dep:kyproto",
]
backend-webtransport-js = [
    "kynet/kynet-webtransport-js",
    "dep:kyproto",
]
js = [
    "kyproto/js",
]
server = [
    "backend-quinn",
]
tokio-rt = [
    "kyproto?/tokio-rt",
]
